brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
reorder_imports = true
max_width = 110
struct_field_align_threshold = 32
imports_indent = "Visual"
indent_style = "Visual"
use_small_heuristics = "Default"